name: 'List repository artifacts'
description: 'List repository artifacts along with the storage consumed'
inputs:
  token:  # id of input
    description: 'GitHub Token'
    required: true
    default: GITHUB_TOKEN
  owner:  # id of input
    description: 'Owner'
    required: true
  repo:  # id of input
    description: 'Repository'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: at-sign
  color: orange
